Repository AY2223S1-CS2103T-T13-1/tp, pull requests merged in 2022-10, with the labels that each got.

#67 Add units tests for the Tutorial Group class
  src/main/java/seedu/address/model/student/TutorialGroup.java
  src/main/java/seedu/address/model/student/UniqueTutorialGroupList.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/student/TutorialGroupTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: testing

#69 Add units tests for the Task class
  build.gradle
  src/test/java/seedu/address/model/task/TaskTest.java
Labels: testing

#94 Refactor StudentListCard.fxml
  src/main/java/seedu/address/ui/StudentListCard.java
  src/main/resources/view/StudentListCard.fxml
Labels: bug

#98 Branch update DG
  docs/DeveloperGuide.md
  src/test/java/seedu/address/logic/commands/tutorialgroup/TutorialGroupListCommandTest.java
Labels: documentation

#109 Add Grade class.
  src/main/java/seedu/address/model/grade/Grade.java
Labels: enhancement

#110 Add tests for the Grade class.
  src/test/java/seedu/address/model/grade/GradeTest.java
Labels: testing

#117 Update the Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#122 Branch update ug
  docs/UserGuide.md
Labels: documentation

#119 Branch test for tutorial group storage
  src/test/java/seedu/address/storage/JsonAdaptedTutorialGroupTest.java
  src/test/java/seedu/address/testutil/TypicalTutorialGroups.java
Labels: testing

#124 Update user guide
  docs/UserGuide.md
  docs/images/TAA.png
Labels: documentation

#126 Grade edit command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/grade/GradeEditCommand.java
  src/main/java/seedu/address/logic/commands/grade/GradeViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/grade/GradeEditCommandParser.java
  src/main/java/seedu/address/logic/parser/grade/GradeViewCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/grade/Grade.java
  src/main/java/seedu/address/model/grade/GradeKey.java
  src/main/java/seedu/address/model/student/GradeMap.java
  src/main/java/seedu/address/model/student/exceptions/DuplicateGradeKeyException.java
  src/main/java/seedu/address/model/student/exceptions/GradeKeyNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedGrade.java
  src/main/java/seedu/address/storage/JsonAdaptedGradeKey.java
  src/main/java/seedu/address/storage/JsonAdaptedGradeTuple.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/grade/EditGradeDescriptorTest.java
  src/test/java/seedu/address/logic/commands/student/StudentAddCommandTest.java
  src/test/java/seedu/address/logic/commands/tutorialgroup/TutorialGroupAddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/grade/GradeTest.java
  src/test/java/seedu/address/testutil/EditGradeDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
Labels: enhancement

#143 Branch add use cases to dg
  docs/DeveloperGuide.md
Labels: documentation

#149 Add Grade commands to User Guide
  docs/UserGuide.md
Labels: documentation
